substitutions:
  my_name: elpriser
  my_friendly_name: Elpriser
  my_comment: Get and show Elprices
  ap_ssid: elpriser-ssd
#  my_board: esp32dev
  my_board: esp32-s3-devkitc-1
  font_mask: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~°æøåÆØÅ"

esphome:
  name: ${my_name}
  friendly_name: ${my_friendly_name}
  comment: ${my_comment}
  min_version: 2025.2.2

esp32:
  board: ${my_board}
  framework:
    type: esp-idf

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${ap_ssid}

api:

logger:
  level: ERROR

web_server:
  port: 80

captive_portal:


<<: !include components/elpriser/elpriser.yaml

# ----- Display section -----
#
# Must hold script with 3 functions:
#script:
#  - id update_table        # is called when next_sex_ and best_sex are filled.
#    parameters:
#      json_data: string    # JSON array with next or best 6 hours
#      container_id: string # Send containerens ID som string
#      then:
#        - lambda: |-
#            //c++ code to place json data into container
#  - id: update_page        # is called when current_price_ is filled.
#      then:
#        - lambda: |-
#            //c++ code to place price on screen and set color
#  - id: update_time        # is called on earch second
#      parameters:
#      timestr: string      # timestring (XX:XX:XX) to be displayed on screen
#      then:
#        - lambda: |-
#            //c++ code to update time on screen

<<: !include components/elpriser/display.yaml
